version: "3"

services:
  database:
    image: postgis/postgis:13-master
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "45432:5432"
    env_file:
      - env/database.env
  backend:
    build: ./backend
    ports:
      - "45000:5000"
    volumes:
      - ./backend/code:/var/opt/gis
  frontend:
    build: ./frontend
    ports:
      - "44200:4200"
    volumes:
      - ./frontend/code/src:/var/opt/gis/src
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "45050:5050"
    restart: always
    env_file: 
      - env/pgadmin.env
volumes:
  database-data:
