version: "3"

services:
  database:
    image: postgis/postgis:13-master
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
    env_file:
      - env/database.env
  pg_featureserv:
    image: pramsey/pg_featureserv:CI
    env_file:
      - env/pg_featureserv.env
    ports:
      - "9000:9000"
    depends_on:
      - "database"
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "25050:${PGA_LISTEN_PORT}"
    restart: always
    env_file: 
      - env/pgadmin.env
volumes:
  database-data:
